# Generated by Django 2.2.3 on 2019-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Varify_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=300, unique=True)),
                ('transaction_id', models.CharField(max_length=300, unique=True)),
                ('bkash_number', models.IntegerField()),
            ],
        ),
    ]
