# Generated by Django 2.2.3 on 2019-12-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='listing',
        ),
    ]
