# Generated by Django 2.2.3 on 2019-12-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0002_auto_20191210_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('created', 'CREATED'), ('paid', 'PAID'), ('shipped', 'SHIPPING'), ('refunded', 'REFUNDED')], default='created', max_length=120),
        ),
    ]
