# Generated by Django 2.2.3 on 2019-12-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
