# Generated by Django 2.2.3 on 2019-11-15 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_type', models.CharField(default=' ', max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('product_logo', models.ImageField(blank=True, default='profile_images/default/default.jpg', max_length=255, upload_to='profile_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 15, 8, 3, 47, 319873, tzinfo=utc))),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
