# Generated by Django 2.2.3 on 2019-11-15 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 8, 6, 30, 816768, tzinfo=utc)),
        ),
    ]
