# Generated by Django 2.2.3 on 2019-12-02 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191202_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 16, 56, 18, 169265, tzinfo=utc)),
        ),
    ]
