# Generated by Django 2.2.3 on 2019-12-03 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191202_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 22, 13, 54, 935239, tzinfo=utc)),
        ),
    ]
