# Generated by Django 2.2.3 on 2019-12-05 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191204_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 16, 22, 29, 236445, tzinfo=utc)),
        ),
    ]
