# Generated by Django 2.2.3 on 2019-12-09 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191205_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 19, 55, 25, 902138, tzinfo=utc)),
        ),
    ]
