# Generated by Django 2.2.3 on 2019-12-09 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191210_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 20, 42, 18, 130304, tzinfo=utc)),
        ),
    ]
