# Generated by Django 2.2.3 on 2019-12-12 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191212_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 21, 9, 13, 413781, tzinfo=utc)),
        ),
    ]
