# Generated by Django 2.2.3 on 2019-12-12 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191213_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 21, 18, 39, 256903, tzinfo=utc)),
        ),
    ]
