# Generated by Django 2.2.3 on 2019-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191204_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('created', 'CREATED'), ('paid', 'PAID'), ('shipped', 'SHIPPING'), ('refunded', 'REFUNDED')], default='created', max_length=120),
        ),
    ]
